wechat:
  grant_type: client_credential
  appid: wxf2e6e6a9808d9874
  secret: d6ac1d669e88db22ba15da305536c591

simulatedData:
  productName: Pencil
  equipmentName: E001
  equipmentId: 1
  area: 天津
  energyRandomMin: 10
  energyRandomMax: 20
  amountRandomMin: 10
  amountRandomMax: 30
  powerTransformer:
    - rawC
    - coke
    - ele
    - steam
  regulatingTransformer:
    - rawC
    - coke
    - ele
    - steam
  audioFrequencyTransformer:
    - rawC
    - coke
    - ele
    - steam
  intermediateFrequencyTransformer:
    - rawC
    - coke
    - ele
    - steam
  highFrequencyTransformer:
    - rawC
    - coke
    - ele
    - steam

test:
  array1: aaa,bbb,ccc
  array2: 111,222,333
  array3: 11.1,22.2,33.3
tenant:
  # 租户前缀
  prefix:
    "tj": "88.155.109"
    "2356b5ce-d69c-4469-b5f6-b44b8dac1510": "88.155.110"
  # 每次定时任务下不同租户的解析数量
  count:
    "tj": 20
    "2356b5ce-d69c-4469-b5f6-b44b8dac1510": 30
  threshold:
    - code: "tj"
      min: 20
      max: 200
    - code: "2356b5ce-d69c-4469-b5f6-b44b8dac1510"
      min: 30
      max: 300